export const STATUS_CODES = {

    // Success
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,

    // Client Errors
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,

    // Server Errors
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
};

export const MESSAGES = {
        REGISTRATION_SUCCESS: "Registration successful",
        LOGIN_SUCCESS: "Login successful",
        LOGOUT_SUCCESS: "Logout successful",
        AUTHENTICATION_REQUIRED: "Authentication required",
        INVALID_TOKEN: "Invalid token",
        TOKEN_EXPIRED: "Token has expired",
        USER_NOT_FOUND: "User not found",
        ACCOUNT_INACTIVE:"Your account is inactive",
        INVALID_CREDENTIALS: "Invalid email or password",
        EMAIL_ALREADY_REGISTERED: "Email is already registered",
        PASSWORD_CHANGED: "Password changed successfully",
        EMAIL_REQUIRED:"Email is required",
        PROVIDE_A_VALID_EMAIL:"Please provide a valid email",
        PASSWORD_REQUIRED:"Password is required",
    
        USER_PROFILE_FETCHED:"Profile fetched successfully",
        USER_PROFILE_UPDATED: "Profile updated successfully",
        USER_ACCOUNT_DELETED:"Account deleted successfully",
        USER_CURRENT_PASSWORD_INCORRECT:"Current password is incorrect",

        PROFILE_NOT_FOUND:"Candidate profile not found",
        PROFILE_FETCHED:"Candidate profile fetched successfully",
        PROFILE_UPDATED:"Candidate profile updated successfully",
        PROVIDE_VALID_URL:"Please provide a valid LinkedIn URL",
        PROVIDE_A_VALID_GITHUB_URL:"Please provide a valid GitHub URL",
        PROVIDE_A_VALID_PORTFOLIO_URL:"Please provide a valid portfolio URL",
        SKILL_ADDED: "Skill added successfully",
        SKILL_REMOVED:"Skill removed successfully",
        SKILL_ALREADY_EXISTS:"Skill already added",
        SKILL_NOT_FOUND:"Skill not found",
        SKILL_ADDED_TO_JOB:"Skill added to job successfully",
        SKILL_REMOVED_FROM_JOB:"Skill removed from job successfully",
        SKILL_MUST_BE_NUMBER:"Skill ID must be a number",
        SKILL_ID_MUST_BE_INT:"Skill ID must be an integer",
        SKILL_ID_MUST_BE_POSITIVE:"Skill ID must be positive",
        SKILL_ID_REQUIRED:"Skill ID is required",

        RECRUITER_PROFILE_NOT_FOUND:"Recruiter profile not found",
        RECRUITER_PROFILE_FETCHED:"Recruiter profile fetched successfully",
        RECRUITER_PROFILE_UPDATED: "Recruiter profile updated successfully",
        PROVIDE_VALID_PHONE_NO:"Please provide a valid Indian phone number",

        COMPANY_CREATED:"Company created successfully",
        COMPANY_FETCHED:"Company fetched successfully",
        COMPANY_UPDATED: "Company updated successfully",
        COMPANY_NOT_FOUND:"Company not found",
        COMPANY_NAME_EXISTS:"Company name already exists",
        PROVIDE_A_VALID_WEB_URL:"Please provide a valid website URL",

        JOB_CREATED:"Job created successfully",
        JOB_FETCHED:"Job fetched successfully",
        JOB_UPDATED: "Job updated successfully",
        JOB_DELETED:"Job deleted successfully",
        JOB_NOT_FOUND:"Job not found",
        JOB_CATEGORY_NOT_FOUND:"Job category not found",
        JOB_NOT_AUTHORIZED_UPDATE:"You are not allowed to update this job",
        JOB_NOT_AUTHORIZED_DELETE: "You are not allowed to delete this job",
        JOB_NOT_OPEN:"This job is not open for applications",
        JOB_DEADLINE_PASSED:"Application deadline has passed",
    
        APPLIED:"Application submitted successfully",
        APPLICATION_FETCHED: "Application fetched successfully",
        APPLICATION_WITHDRAWN: "Application withdrawn successfully",
        APPLICATION_STATUS_UPDATED:"Application status updated successfully",
        APPLICATION_NOT_FOUND: "Application not found",
        ALREADY_APPLIED:"You have already applied for this job",
        CANNOT_WITHDRAW:"This application cannot be withdrawn",
        WITHDRAWN_CANNOT_UPDATE:"Withdrawn applications cannot be updated",
        APPLICATION_NOT_AUTHORIZED:"You are not authorized to view this application",
        NOT_AUTHORIZED_UPDATE:"You are not authorized to update this application",
        APPLICATION_NOT_AUTHORIZED_TO_ACCESS:"You are not authorized to access this resource",
        INVALID_APPLICATION_STATUS:"Invalid application status",
        APPLICATION_STATUS_REQUIRED:"Application status is required",

        JOB_SAVED:"Job saved successfully",
        JOB_REMOVED:"Job removed from saved jobs",
        JOB_ALREADY_SAVED:"Job is already saved",
        SAVED_JOB_NOT_FOUND:"Saved job not found",

        INTERVIEW_SCHEDULED:"Interview scheduled successfully",
        INTERVIEW_FETCHED:"Interview fetched successfully",
        INTERVIEW_UPDATED:"Interview updated successfully",
        INTERVIEW_CANCELLED:"Interview cancelled successfully",
        INTERVIEW_NOT_FOUND:"Interview not found",
        INTERVIEW_NOT_AUTHORIZED:"You are not authorized to manage this interview",
        INTERVIEW_STATUS_UPDATED:"Interview status updated successfully",
        VALID_INTERVIEW_DATE:"Please provide a valid interview date",
        INTERVIEW_DATE_REQUIRED:"Interview date is required",
        INVALID_INTERVIEW_TYPE:"Invalid interview type",
        INTERVIEW_TYPE_REQUIRED:"Interview type is required",
        INVALID_INTERVIEW_STATUS:"Invalid interview status",
        INTERVIEW_STATUS_REQUIRED:"Interview status is required",

        NOTIFICATION_FETCHED:"Notifications fetched successfully",
        NOTIFICATIONS_MARKED_READ:"Notification marked as read",
        NOTIFICATIONS_ALL_MARKED_READ:"All notifications marked as read",
        NOTIFICATIONS_DELETED:"Notification deleted successfully",
        NOTIFICATIONS_ALL_DELETED:"All notifications deleted successfully",
        NOTIFICATIONS_NOT_FOUND:"Notification not found",

        JOB_CATEGORY_CREATED:"Job category created successfully",
        JOB_CATEGORY_FETCHED:"Job categories fetched successfully",
        JOB_CATEGORY_UPDATED:"Job category updated successfully",
        JOB_CATEGORY_DELETED:"Job category deleted successfully",
        JOB_CATEGORY_NOT_FOUND:"Job category not found",
        JOB_CATEGORY_ALREADY_EXISTS:"Job category already exists",

        VALIDATION_FAILED:"Validation failed",
        REQUIRED_FIELDS:"Required fields are missing",
        INVALID_ID_PROVIDED:"Invalid ID provided",

        SUCCESS:"Operation successful",
        SOMETHING_WENT_WRONG:"Something went wrong",
        INTERNAL_SERVER_ERROR:"Internal server error",
        NO_DATA_FOUND:"No data found",
        TOO_MANY_REQUESTS:"Too many requests. Please try again later.",
        TOO_MANY_AUTHENTICATION_REQUESTS:"Too many authentication requests. Please try again later.",
        TOO_MANY_LOGIN_REQUESTS:"Too many login requests. Please try again later.",
};